### ISSUE TITLE
Eclipse FloatArrayList support

### ISSUE THREAD

**Issue by wenbostar** [jerolba/parquet-carpet#47]
Hi,

I tried to use parquet-carpet to read a parquet file with java record as shown below:

```java
import org.eclipse.collections.impl.list.mutable.primitive.FloatArrayList;

public record DataRecord(
                             int index,
                             FloatArrayList a,
                             FloatArrayList b,
                             double c) {
}

public void test(){
    CarpetReader<DataRecord> reader = new CarpetReader<>(new File("test.parquet"), DataRecord.class);
    for (DataRecord r: reader) {
        ...  
    }

}
```

I got the following error. It seems parquet-carpet does not support Eclipse FloatArrayList.

```
Exception in thread "main" com.jerolba.carpet.RecordTypeConversionException: Field 'a' is not a collection in 'test$DataRecord' mapping column 'a'
	at com.jerolba.carpet.impl.read.SchemaFilter.filter(SchemaFilter.java:99)
	at com.jerolba.carpet.impl.read.SchemaFilter.project(SchemaFilter.java:60)
	at com.jerolba.carpet.impl.read.CarpetReadSupport.init(CarpetReadSupport.java:59)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:198)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:170)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:139)
	at com.jerolba.carpet.CarpetReader$RecordIterator.<init>(CarpetReader.java:227)
	at com.jerolba.carpet.CarpetReader.buildIterator(CarpetReader.java:201)
	at com.jerolba.carpet.CarpetReader.iterator(CarpetReader.java:156)

```

It works when I use List but it is slow due to boxing/unboxing overhead. Is there a way to make it work with Eclipse FloatArrayList?

```
public record DataRecord(
                             int index,
                             List<Float> a,
                             List<Float> b,
                             double c) {
}
```

**Comment by jerolba** [comment]
Hi Bo.

Carpet only supports collections that:
* implement List or Set interfaces
* provide a constructor without parameters

I know the advantages of FloatArrayList using primitive floats, but Carpet now doesn't support to customize how to deserialize any type of objects (remember it only supports Records, not normal classes).

It's not in the short term roadmap to support "modules" like [Jackson](https://github.com/FasterXML/jackson-datatypes-collections/)

I know that there is an overhead, but my only proposal is to deserialize to Java List and streaming the file, map the object to your final representation:

```java
public record DataRecordRead(
                             int index,
                             List a,
                             List b,
                             double c) {
    public DataRecord map() {
          return new DataRecord(index, converFloatList(a), converFloatList(b), c);
    }
}

public record DataRecord(
                             int index,
                             FloatArrayList a,
                             FloatArrayList b,
                             double c) {
}

CarpetReader<DataRecordRead> reader = new CarpetReader<>(new File("test.parquet"), DataRecordRead.class);
    for (DataRecordRead read: reader) {
        DataRecord r = read.map();

    }
```
